# Railway Server Port
server.port=${PORT:8080}

# Railway MySQL Database via ENV Variables
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:${DB_URL}

# JPA / Hibernate Production Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
